# This opens a pull request to main everytime someone pushes to a release branch.

name: Release -> Main PR

on:
  push:
    branches: "release-*"

jobs:
  pull-request:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Open PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Update main from ${{ steps.branch-name.outputs.current_branch }}
          pr_body: ":rocket: *An automated PR* - Please make any changes needed to resolve merge conflicts and then approve and merge!"
          pr_reviewer: "jsignell,${{ github.actor }}"
