name: Continuous Integration

# always run CI on new commits to any branch
on:
  pull_request:
  push:
    branches:
      - "release*"
      - main

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    env:
      REF: release-2021.10.26 # ${{ github.base_ref || github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: linting
          - task: validating-examples
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.7
      - name: linting
        if: matrix.task == 'linting'
        shell: bash
        run: |
          pip install --upgrade black[jupyter] flake8 nbqa
          make lint
      - name : validate-release
        if: ${{ matrix.task == 'validating-examples' && contains(env.REF, 'release')}}
        env:
          BRANCH: $(echo ${{env.REF}} | cut -d- -f2)
        shell: bash
        run: |
          pip install --upgrade requests jsonschema
          echo examples branch: ${{env.REF}}
          echo recipe schema branch: ${{env.BRANCH}}
          python .ci/validate-examples.py --examples-dir $(pwd)/examples --recipe-schema-branch ${{ env.BRANCH }}
      - name : validate
        if: ${{ matrix.task == 'validating-examples' && !contains(env.REF, 'release')}}
        shell: bash
        run: |
          pip install --upgrade requests jsonschema
          echo examples branch: ${{env.REF}}
          echo recipe schema branch: main
          make validate
